########################################################################################################################
# File name: txt_to_geotiff.py
# Author: Mike Gough
# Date created: 07/19/2023
# Python Version: 3.x
# Description:
# Converts txt (csv) files into ascii rasters and then geotiffs.
# The txt (csv) files received don't have any spatial information in them. They are just txt (csv) files containing
# data values by row and column -- a subset of the CFO data extent (the row and column range was generated by the
# get_rows_ans_cols.py script).
# This script opens up the text file, adds an ascii header, and replaces commas with spaces -- thereby making an ascii
# raster. This is then converted to a geotiff.
########################################################################################################################

import os
import shutil
import glob
from osgeo import gdal

#input_dir = r"\\loxodonta\GIS\Source_Data\biota\region\NEON_Sites\SOAP\shrubs_and_trees_from_werne\little_tree_base_heights\b_lt_1"
#ascii_dir = r"G:\CALFIRE_Decision_support_system_2021_mike_gough\Tasks\NEON\Data\Intermediate\Text_File_to_GeoTiff\ascii\b_lt_1"
#geotiff_dir = r"G:\CALFIRE_Decision_support_system_2021_mike_gough\Tasks\NEON\Data\Intermediate\Text_File_to_GeoTiff\geotiff\b_lt_1"

input_dir = r"\\loxodonta\GIS\Source_Data\biota\region\NEON_Sites\SOAP\shrubs_and_trees_from_werne\little_tree_base_heights\b_lt_0"
ascii_dir = r"G:\CALFIRE_Decision_support_system_2021_mike_gough\Tasks\NEON\Data\Intermediate\Text_File_to_GeoTiff\ascii\b_lt_0"
geotiff_dir = r"G:\CALFIRE_Decision_support_system_2021_mike_gough\Tasks\NEON\Data\Intermediate\Text_File_to_GeoTiff\geotiff\b_lt_0"

# Coordinate system
srs = "EPSG:32610"

# ASCII header params
ncols = 1456
nrows = 1425
xllcorner = 826260
yllcorner = 4099480
cellsize = 10
nodata_value = -32768

text_files = glob.glob(input_dir + "/*.txt")

for text_file in text_files:
    file_name = os.path.basename(text_file).split(".")[0]
    print(file_name)
    ascii_file = os.path.join(ascii_dir, file_name + ".asc")
    shutil.copyfile(text_file, ascii_file)
    with open(ascii_file, "r") as f:
        csv_text = f.read()
        ascii_text = csv_text.replace(",", " ")
    with open(ascii_file, "w") as f:
        f.write("ncols " + str(ncols) + "\n")
        f.write("nrows " + str(nrows) + "\n")
        f.write("xllcorner " + str(xllcorner) + "\n")
        f.write("yllcorner " + str(yllcorner) + "\n")
        f.write("cellsize " + str(cellsize) + "\n")
        f.write("nodata_value " + str(nodata_value) + "\n")
        f.write(ascii_text)
    geotiff_file = os.path.join(geotiff_dir, file_name + ".tif")
    ascii_ds = gdal.Open(ascii_file)
    gdal.Translate(geotiff_file, ascii_ds, outputSRS="EPSG:32610")
